nodeLinker: pnp

packageExtensions:
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-scripts@*:
    dependencies:
      autoprefixer: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
