name: 🚀 Deploy website on push
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'web/**'

env:
  PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.PUBLIC_RECAPTCHA_SITE_KEY }}
  PUBLIC_ALT_FORM_URL: ''
  SMTP_FROM: ${{ secrets.SMTP_FROM }}
  SMTP_HOST: ${{ vars.SMTP_HOST }}
  SMTP_PASS: ${{ secrets.SMTP_PASS }}
  SMTP_PORT: ${{ vars.SMTP_PORT }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - run: npm -w=web ci
      - run: npm -w=web run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ vars.FTP_SERV }}
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: application/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**

      - name: Restart File Creation
        run: |
          mkdir -p /tmp/r
          head /dev/urandom | tr -dc A-Za-z0-9 | fold -w 16 | head -n 1 > /tmp/r/restart.txt

      - name: Send restart file
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ vars.FTP_SERV }}
          username: ${{ vars.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: /tmp/r/
          server-dir: application/tmp/
